master:
  push:
    - name: "sync to github"
      imports: https://cnb.cool/puresky/secret-store/-/blob/main/github.yml
      stages:
        image: tencentcom/git-sync
        settings:
          target_url: https://github.com/PureSkys/ApiHub.git
          auth_type: https
          username: ${GIT_USERNAME}
          password: ${GIT_ACCESS_TOKEN}
    - name: "sync to gitee"
      imports: https://cnb.cool/puresky/secret-store/-/blob/main/gitee.yml
      stages:
        image: tencentcom/git-sync
        settings:
          target_url: https://gitee.com/pureskys/api-hub.git
          auth_type: https
          username: ${GIT_USERNAME}
          password: ${GIT_ACCESS_TOKEN}