master:
  push:
    - name: "sync git run"
      stages:
        - name: "sync to github"
          imports: https://cnb.cool/puresky/secret-store/-/blob/main/github.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/PureSkys/ApiHub.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
        - name: "sync to gitee"
          imports: https://cnb.cool/puresky/secret-store/-/blob/main/gitee.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://gitee.com/pureskys/api-hub.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
    - services:
        - docker #声明后，流水线内可以直接使用docker命令
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest"
          exports:
            info: IMAGE_TAG

        - name: docker build
          script: docker build -t $IMAGE_TAG .

        - name: push image
          script: docker push $IMAGE_TAG