"""init1

Revision ID: 3cab4d9c55fc
Revises: 5ed44ae0725c
Create Date: 2026-02-18 21:35:58.149852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3cab4d9c55fc'
down_revision: Union[str, Sequence[str], None] = '5ed44ae0725c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentence_category', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentence_category', 'description')
    # ### end Alembic commands ###
