"""ini2

Revision ID: 570a79a34eca
Revises: e638fd5df542
Create Date: 2026-02-11 15:35:47.213872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '570a79a34eca'
down_revision: Union[str, Sequence[str], None] = 'e638fd5df542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sentence_content_content'), 'sentence_content', ['content'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentence_content_content'), table_name='sentence_content')
    # ### end Alembic commands ###
