"""init666

Revision ID: d10f7426fa5b
Revises: facf9f501ef0
Create Date: 2026-02-13 21:23:37.318019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd10f7426fa5b'
down_revision: Union[str, Sequence[str], None] = 'facf9f501ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sentence_user_config_user_id_fkey'), 'sentence_user_config', type_='foreignkey')
    op.create_foreign_key(None, 'sentence_user_config', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sentence_user_config', type_='foreignkey')
    op.create_foreign_key(op.f('sentence_user_config_user_id_fkey'), 'sentence_user_config', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
