"""init

Revision ID: e638fd5df542
Revises: 
Create Date: 2026-02-11 15:30:45.208119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e638fd5df542'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_category_category'), 'sentence_category', ['category'], unique=True)
    op.create_index(op.f('ix_sentence_category_id'), 'sentence_category', ['id'], unique=False)
    op.create_table('sentence_content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_who', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['sentence_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_content_id'), 'sentence_content', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentence_content_id'), table_name='sentence_content')
    op.drop_table('sentence_content')
    op.drop_index(op.f('ix_sentence_category_id'), table_name='sentence_category')
    op.drop_index(op.f('ix_sentence_category_category'), table_name='sentence_category')
    op.drop_table('sentence_category')
    # ### end Alembic commands ###
